# Experiment List Configuration - INI Format
# Experiments grouped by number of qubits required

[calibration]
version_extractor = enabled
bell_tomography = disabled


[1]
reuploading_classifier = disabled
coherence = enabled
readout = enabled
standard_rb = disabled
; ###universal_approximant = disabled

[2]
grover2q = enabled
process_tomography = disabled

[3]
ghz = enabled
mermin = enabled
grover3q = enabled
qft = disabled
qft3_swap = enabled
amplitude_encoding = disabled
qml_3q_yeast = disabled
qml_3q_statlog = disabled

[4]
ghz = enabled
mermin = enabled

[5]
ghz = enabled
mermin = enabled
